### ISSUE TITLE
[QOL] When requesting a certificate, it'd be great to have feedback for UX.

### ISSUE THREAD

**Issue by patrick-leb** [ymirapp/cli#10]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/68301566/137981347-d11c7e0f-dbc0-4e4b-84fd-d0b200dffd0b.png">

After pressing enter, nothing happens for a few dozen seconds. I wondered if it was bugged or needed more input. 

Suggestion: after pressing enter, return something along the lines of 
`Please wait while requesting the certificate....this process can take a few minutes`

**Comment by carlalexander** [comment]
If you request a certificate for a domain managed by Ymir, the certificate gets issued right away. If it isn't, there's actually a warning below the DNS records. You truncated it out of your screenshot, but it says:

>The SSL certificate won't be issued until these DNS record(s) are added
