### ISSUE TITLE
allow attaching tags on the resource created/manged by Ymir

### ISSUE THREAD

**Issue by selul** [ymirapp/cli#20]
A useful enhancement for Ymir would be to automatically add tags to resources based on the project and environment names. This feature would enable easy filtering of resources in the AWS cost explorer, allowing for more granular cost analysis by the project.

**Comment by carlalexander** [comment]
Yeah, as @patrick-leb said, it's being worked on right now. I'm getting closer to having it done. Ymir will insert a bunch of tags on all resources it manages. You'll also be able to define tags for each environment as well in the `ymir.yml` file.

**Comment by carlalexander** [comment]
@selul this is officially live. Please refer to the [`tags`](https://docs.ymirapp.com/reference/configuration.html#tags) configuration option.

The only thing missing is retroactively tagging team resources such as database servers, cache servers, networks, etc. Once that's done later this week, I will close the ticket.

**Comment by carlalexander** [comment]
Took a bit longer to get to this, but all team resources are tagged now. 🙂
