### ISSUE TITLE
Copy Command ignores the vcs ignored files if those are present in build.include

### ISSUE THREAD

**Issue by selul** [ymirapp/cli#21]
Considering the following file structure and contents. 

**.gitignore**
```.gitignore
web/app/themes/*/
!web/app/themes/theme
node_modules
```
**ymir.yml**
```yml
...
    build:
      include:
        - web/app/themes/theme
```

When the copy is being done, if the theme folder has a node_modules folder, this is being added to the deployment, despite the fact the folder is being ignored on .gitignore. 

I think this is happening because we include the build.include on the last step. https://github.com/ymirapp/cli/blob/main/src/Build/CopyWordPressFilesStep.php which copy over the gitignored files. 

A possible solution that I see is to apply the `$finder->ignoreVCSIgnored(true);` at the very end. 

This is currently causing the copy of thousands of node_modules files to s3.

**Comment by carlalexander** [comment]
I think you can fix this by removing the `build.include` option. The finder component is pretty finicky about `.gitignore` formatting. I've opened a few issues about it. If you look at the `.gitignore` for carlalexander.ca [here](https://github.com/carlalexander/carlalexander.ca/blob/master/.gitignore), you'll see what I mean.

I'd change yours to be something like this:

```gitignore
web/app/themes/*/
!web/app/themes/theme/**
node_modules
```

Can you let me know if that fixes the issue?

**Comment by selul** [comment]
Yes, this seems to work.

**Comment by carlalexander** [comment]
Awesome! Closing this 🙂
