### ISSUE TITLE
Option to turn off Cloudwatch logging. 

### ISSUE THREAD

**Issue by selul** [ymirapp/cli#25]
It would be good to have a setting to turn off Cloudwatch logging if we use different services like Axiom to send logs.

I've tried to remove the permissions manually from the Role that the Lambda function uses, i.e.: 
```
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
```
But they are added back at each new deployment.

**Comment by selul** [comment]
A workaround that I did to accomplish this is to add an extra policy to the execution role to deny Cloudwatch access, as seen here https://vertis.d.pr/i/IL4Sjp

This seems to do the job for now.

**Comment by carlalexander** [comment]
There's now a [`logging`](https://docs.ymirapp.com/reference/configuration.html#logging) that control the environment's IAM role so that this can be disabled.
