### ISSUE TITLE
Running wp CLI commands is awkward

### ISSUE THREAD

**Issue by markjaquith** [ymirapp/cli#5]
Works:

* `ymir wp "user list"`

Does not work:

* `ymir wp user list`
* `ymir wp -- user list`

Having to quote the WordPress command is incredibly awkward. Imagine commands which themselves have to be quoted.

When I use Pantheon's Terminus tool (a CLI for interacting with their hosting platform) I can do `terminus remote:wp sitename.live -- user list`. The `--` there signifies "I'm done passing options to `terminus`, and the rest of everything should be passed to `wp` on the remote host" and is quite handy.

**Comment by carlalexander** [comment]
Yeah, I just made it the same way Vapor runs CLI commands, but that's actually a pretty nice way to handle it.
