### ISSUE TITLE
`import:uploads` sftp doesn't support ed25519 keys

### ISSUE THREAD

**Issue by rjocoleman** [ymirapp/cli#6]
When using sftp `import:uploads` parses a url, sends it to [`League\Flysystem\PhpseclibV2\SftpConnectionProvider`](https://github.com/ymirapp/cli/blob/master/src/Command/Import/ImportUploadsCommand.php#L195)

`PhpseclibV2` doesn't support ed25519 keys. The logic in [`SftpConnectionProvider`](https://github.com/thephpleague/flysystem/blob/65bf14d6ac610bb0054d43a82dca83d07cc34032/src/PhpseclibV2/SftpConnectionProvider.php#L161-L170) is to use an agent unless opt'd out (7th parameter of `SftpConnectionProvider`). 

I suggest two workarounds:

1.) if password is specified set `useAgent = false`.

2.) add an additional cli argument to disable agent.

`PhpseclibV3` support is also [available](https://github.com/thephpleague/flysystem-sftp-v3). I haven't looked into it (unsure about backwards compat).

https://github.com/thephpleague/flysystem/issues/1261

I'll open a PR for workaround 1 as it seems sane to me. Of course both of these only handle the case where password access is available!

**Comment by carlalexander** [comment]
I'll bump the version of phpseclib when I can. They haven't released a new version with v3 support yet. I'll open another issue for it.
