### ISSUE TITLE
Add support for PhpSecLibv3

### ISSUE THREAD

**Issue by carlalexander** [ymirapp/cli#9]
As discussed in #6, need to wait until next release of flysystem

**Comment by rjocoleman** [comment]
There's this, but I'm not familiar with these libraries https://github.com/thephpleague/flysystem-sftp-v3

**Comment by carlalexander** [comment]
Unfortunately, it looks like [they dropped support for PHP 7 before tagging the release](https://github.com/thephpleague/flysystem-sftp-v3/commit/e0930123be0217d04bd3c13422af4d750b56bbb0#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34). So I won't be able to add support for this. 😞
